ZO_CreateStringId("SI_LCK_SCAN_START"                , "Scanning item table; this occurs only once per major game update.")
ZO_CreateStringId("SI_LCK_SCAN_COMPLETE"             , "Scan complete.")

ZO_CreateStringId("SI_LCK_SETTINGS_TITLE"            , "Character Knowledge: Data (LibCharacterKnowledge)")
ZO_CreateStringId("SI_LCK_SETTINGS_CHATCOMMAND"      , "This addon settings panel can also be accessed via the |c00CCFF/lck|r chat command.")

ZO_CreateStringId("SI_LCK_SETTINGS_USE_DEFAULT"      , "Use default")

ZO_CreateStringId("SI_LCK_SETTINGS_TRACKING1"        , "Do not track")
ZO_CreateStringId("SI_LCK_SETTINGS_TRACKING2"        , "Track low quality")
ZO_CreateStringId("SI_LCK_SETTINGS_TRACKING3"        , "Track medium quality")
ZO_CreateStringId("SI_LCK_SETTINGS_TRACKING4"        , "Track all")

ZO_CreateStringId("SI_LCK_SETTINGS_PRIORITY"         , "Priority Class")
ZO_CreateStringId("SI_LCK_SETTINGS_PRIORITY_HELP"    , "Multiple characters can share the same priority class; characters within the same priority class are ranked by seniority, with older characters given precedence over newer characters.")

ZO_CreateStringId("SI_LCK_SETTINGS_EXPORT"           , "Select for Export")

ZO_CreateStringId("SI_LCK_SETTINGS_MAIN_SECTION"     , "Tracking and Priority")
ZO_CreateStringId("SI_LCK_SETTINGS_RANKING_PREVIEW"  , "Current character ranking order")
ZO_CreateStringId("SI_LCK_SETTINGS_SYSTEM_DEFAULTS"  , "These system-wide defaults will apply for every character unless overridden at the server, account, or character level.")
ZO_CreateStringId("SI_LCK_SETTINGS_SERVER_DEFAULTS"  , "These server-wide defaults will apply for every character on this server unless overridden at the account or character level.")
ZO_CreateStringId("SI_LCK_SETTINGS_ACCOUNT_DEFAULTS" , "These account-wide defaults will apply for every character belonging to this account unless overridden at the character level.")

ZO_CreateStringId("SI_LCK_SETTINGS_SHARE_SECTION"    , "Share Data")
ZO_CreateStringId("SI_LCK_SETTINGS_SHARE_CAPTION"    , "Export and copy, or paste and import, to share data")
ZO_CreateStringId("SI_LCK_SETTINGS_SHARE_EXPORTC"    , "Export Current")
ZO_CreateStringId("SI_LCK_SETTINGS_SHARE_EXPORTCT"   , "Export knowledge data for the current character")
ZO_CreateStringId("SI_LCK_SETTINGS_SHARE_EXPORTA"    , "Export All")
ZO_CreateStringId("SI_LCK_SETTINGS_SHARE_EXPORTAT"   , "Export knowledge data for every enabled character")
ZO_CreateStringId("SI_LCK_SETTINGS_SHARE_EXPORTS"    , "Export Selected (%d)")
ZO_CreateStringId("SI_LCK_SETTINGS_SHARE_EXPORTST"   , "Export knowledge data for characters with \"Select for Export\" enabled")
ZO_CreateStringId("SI_LCK_SETTINGS_SHARE_IMPORT"     , "Import")
ZO_CreateStringId("SI_LCK_SETTINGS_SHARE_CLEAR"      , "Clear")

ZO_CreateStringId("SI_LCK_SETTINGS_RESET_SECTION"    , "Reset Data")
ZO_CreateStringId("SI_LCK_SETTINGS_RESET_WARNING"    , "This will reset all settings, delete all data associated with LibCharacterKnowledge, and reload the UI.")

ZO_CreateStringId("SI_LCK_SETTINGS_NOSAVE_SECTION"   , "Excluded Accounts")
ZO_CreateStringId("SI_LCK_SETTINGS_NOSAVE_CAPTION"   , "List of account names, separated by commas, to exclude from being saved")

ZO_CreateStringId("SI_LCK_SHARE_EXPORT_LIMIT"        , "Skipped [%s/%s]; data limit reached.")
ZO_CreateStringId("SI_LCK_SHARE_IMPORT_STALE"        , "Skipped [%s/%s]; current data is more recent.")
ZO_CreateStringId("SI_LCK_SHARE_IMPORT_API"          , "Skipped [%s/%s]; imported data was generated by a different version of the game.")
ZO_CreateStringId("SI_LCK_SHARE_IMPORT_DONE"         , "Imported [%s/%s]. (%s)")
ZO_CreateStringId("SI_LCK_SHARE_IMPORT_INVALID"      , "Aborting import; corrupted data encountered.")
ZO_CreateStringId("SI_LCK_SHARE_IMPORT_BADVERSION"   , "Imported data was encoded by an incompatible version of LibCharacterKnowledge; please ensure that both users have updated to the latest version of LibCharacterKnowledge.")
ZO_CreateStringId("SI_LCK_SHARE_IMPORT_NEWCHARACTER" , "You have imported one or more new characters that did not previously exist in the database; |c00CCFF/reloadui|r may be necessary for newly-added characters to appear in menus and settings.")
ZO_CreateStringId("SI_LCK_SHARE_IMPORT_TALLY"        , "%d characters imported.")
